### ISSUE TITLE
Great ! That's very excellent work ! 

### ISSUE THREAD

**Issue by bitpeach** [a358003542/xelatex-guide-book#1]
- After I searched lots of places on the Internet, I now find one template by dear you which can be working successfully on MacTex.
- I can't help leaving this message to present my thank and greatest admiration.
- This xelatex-guide-book is very nice coding work, which is not only a series of guidebooks to teach us how to code latex but also a practical latex template using by us.
- Thank you.

**Comment by a358003542** [comment]
@bitpeach  With a  great pleasure to hear that.
