### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by kexplorning** [a358003542/xelatex-guide-book#2]
看了之后，感觉有很多问题。。。

1. 英文省略号用 `\ldots` 没有问题，但是中文省略号的输入方式就是平时的输入方式（……），另外，中文省略号在排版上要求居中，所以 `\ldots` 是不能用在中文省略号上的。
2. 有关波浪号：波浪号非常麻烦，建议去看看 Unicode 码表中有多少个和波浪号有关的字符。中文波浪号应该是全角波浪号。
3. 不需要特别进行中文化，已经有 `ctex` 宏包了。有了 `ctex` 宏包，也就不用使用 `titlesec` 宏包了。
4. 字体小节的解释比较混乱，建议详细解释 OT1 T1 TFM 等 TeX 专用字体与 OTF 与 TTF 字体的用法不同；不然前一节还在说 OT1 T1 等字体，后面就跳到了 OTF TTF 字体，会被人误解。
5. 数学中的分数，行内公式的分数不建议使用行间大小，因为这样会使整行被撑大，行距增加；更建议使用 `$1/2$` 或者 `xfrac` 宏包提供的功能
6. 不要用 `$$...$$`，这应该有很多资料强调过了吧。。。
7. `mathbf显示效果并不是很理想（因为其是跳出数学环境了的，可能设置好mathbf对应的字体显示效果就会变好了。）` 这句解释不对。。`$\mathbf{F}$` 用的是 衬线体 + 粗体，而 `$\boldsymbol{F}$` 用的是 衬线体 + 粗体 + 意大利斜体

没有细看，现在只找到这些问题。

---

现在入门教程满大街，但是有高级内容的教程不多。

请加油。

**Comment by a358003542** [comment]
@kexplorning 这个项目我有时间还有继续维护，现在临时回复如下：
1. 你关于中文省略号的说法是正确的，但这最好不要使用latex命令，而是直接通过输入法输入中文字符。这块知识严格来说不属于latex了。这个可能会考虑补充说明下。
2. 同上。
3. ctex宏包底层仍然是依赖于xetex和文章提到的几个字体处理宏包，个人更喜好底层的DIY，大量引入ctex宏包有时引起一些奇奇怪怪的问题或者其他排版上限定死了的东西，本文就教学目的来说不便于使用ctex宏包。
4. 字体这章实际上已经说得很多了，再说可能会有喧宾夺主的嫌疑，字体这块背景知识很丰富，初接触可能还是会有点迷糊，这块有时间可以考虑再思考整理一下。
5. xfrac宏包我会了解下
6. 不知道你所谓的不要使用 $$ 出处何在，实际上使用 $$ 不光在latex上好用，在mathjax上也很好用，反而有些命令环境支持性不是那么广泛。
7. 这个是我没表述好，老实说我现在自己看这句话也蒙了。。这段需要查阅资料重新写。主要是mathbf和mathbb之类的命令到底干了什么事要弄清楚，你说的衬线体 + 粗体之类只是观察的表象，其内在严格来说涉及到的工作有：根据输入到的F字母命令进行，字符编码映射，字体选择，可能的字族，字形字型的选择。

**Comment by kexplorning** [comment]
1. 嗯。。怎么说呢。。。虽然不属于 latex，但这也算基本排版知识（根据我的了解，貌似不知道怎么正确打中文省略号的也大有人在……），以及这也算在 latex 下妥协产物（大概吧）。。。我也见过全篇 `tex` 用 `\ldots\ldots` 作为中文省略号的。。。
2. 
3. 嗯，ctex 的自定义文档功能个人认为满足大部分用户需求（真的很高度自定义了，它引入的宏比 `titlesec` 还要多，而且使用方式更现代，`tltlesec` 这几个大括号我填到后面就忘了这项是用来干嘛的。。），不知道你说的奇奇怪怪的问题是指什么
4. 字体是大坑，入坑需谨慎。。。隔壁某人入坑后，现在在苦逼地做字体（逃
5. 
6. `$$...$$` 真的有非常多的教程与说明提醒不要使用，比如 `lshort-zh`，比如“一份其实很短的 LaTeX 入门文档”，比如 `latex2e.pdf`。你可以在 TeX Stack Exchange 上面看到详细讨论。另外，额，那其实不是 MathJax 规定的 `$$...$$`，而是标记语言规定的；在 Markdown （方言）里面使用数学公式的语法非常混乱，有的支持 `$...$` `$$...$$` 有的支持 `\(...\)` `\[...\]` 有的全支持，有的是自己的语法。。。
7. 我之前所说的只是最后的实际效果。。有关字体选择的话，默认数学字体用的还是老的 TeX 字体，然而引入 fontspec 宏包会改写数学字体命令。。有的命令还引入文本模式中的字体。。反正很麻烦就对了。。

**Comment by a358003542** [comment]
@kexplorning 

1 已修改为： 英文输入法下直接输入三个小数点和使用 \verb+\ldots+ 命令区别不大，中文省略号请使用中文输入法下的全角模式下的省略号。

2. 已补充 ——这里所谓的Rime输入法意思就是中文输入法下的全角输入。

3，4 closed 

5  分数表达使用 frac命令是没有问题的，不清楚你这里说的使用行间大小是那里，本书并没有这样说。 关于xfrac宏包本书不想引入太多复杂度。 closed.

6  非常多的人这么说不代表就是正确的，Latex数学环境推荐使用 `$` 和 `$$` 这是没有问题的，closed.

7 表述已修改为：
比如物理上力的矢量表示（以区分力的分量$ F_x $），则需要符号加粗。

$ \boldsymbol{F} $    \verb+\boldsymbol{F}+

$ \mathbf{F} $    \verb+\mathbf{F}+

总的来说个人推荐物理学上表示力的矢量推荐用 boldsymbol 命令来封装，而数学意义上的某个向量则推荐用 mathbf 命令来封装\footnote{参考amsmath官方文档9.3小节，mathbf通常用于数学环境下的拉丁字母加粗显示，但是对于其他数学符号是没有效果的，正因为如此amsmath宏包才又提供了boldsymbol来应对那些没有效果的情况，如果该符号在你的数学字体集（math font set）下是有粗体的话。}。

**Comment by a358003542** [comment]
this issue will be auto closed in two weeks.
